spring:
   application:
      name: medialoader
   server:
     port: 8080
   datasource:
      url: jdbc:postgresql://localhost:5432/medialoaderdb
      username: postgres
      password: Medialoader2019
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            temp: 
               use_jdbc_metadata_defaults: false
flyway:
   url: jdbc:postgresql://localhost:5432/medialoaderdb
   user: postgres
   password: Medialoader2019
   baselineVersion: 1.0

services:
   api:
      facebook:
         graph:
            url: https://graph.facebook.com/v4.0
